// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:teamId/invite/:inviteId": {
    params: {
      "teamId": string;
      "inviteId": string;
    };
  };
  "/signup": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/create-team": {
    params: {};
  };
  "/:teamId": {
    params: {
      "teamId": string;
    };
  };
  "/:teamId/:channelId": {
    params: {
      "teamId": string;
      "channelId": string;
    };
  };
  "/:teamId/:channelId/:messageId": {
    params: {
      "teamId": string;
      "channelId": string;
      "messageId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:teamId/invite/:inviteId" | "/signup" | "/login" | "/create-team" | "/:teamId" | "/:teamId/:channelId" | "/:teamId/:channelId/:messageId";
  };
  "routes/$teamId.invite.$inviteId.tsx": {
    id: "routes/$teamId.invite.$inviteId";
    page: "/:teamId/invite/:inviteId";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/signup" | "/login";
  };
  "routes/_auth.signup.tsx": {
    id: "routes/_auth.signup";
    page: "/signup";
  };
  "routes/_auth.login.tsx": {
    id: "routes/_auth.login";
    page: "/login";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/create-team" | "/:teamId" | "/:teamId/:channelId" | "/:teamId/:channelId/:messageId" | "/";
  };
  "routes/_app.create-team.tsx": {
    id: "routes/_app.create-team";
    page: "/create-team";
  };
  "routes/_app.$teamId.tsx": {
    id: "routes/_app.$teamId";
    page: "/:teamId" | "/:teamId/:channelId" | "/:teamId/:channelId/:messageId";
  };
  "routes/_app.$teamId.$channelId.tsx": {
    id: "routes/_app.$teamId.$channelId";
    page: "/:teamId/:channelId" | "/:teamId/:channelId/:messageId";
  };
  "routes/_app.$teamId.$channelId.$messageId.tsx": {
    id: "routes/_app.$teamId.$channelId.$messageId";
    page: "/:teamId/:channelId/:messageId";
  };
  "routes/_app.$teamId._index.tsx": {
    id: "routes/_app.$teamId._index";
    page: "/:teamId";
  };
  "routes/_app._index.tsx": {
    id: "routes/_app._index";
    page: "/";
  };
};